# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import secret.models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0008_auto_20171012_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='image',
            field=models.ImageField(null=True, upload_to=secret.models.image_path),
        ),
        migrations.AlterField(
            model_name='piece',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
