# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0009_auto_20171016_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='etc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watch',
            name='end',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watch',
            name='start',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
