# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0010_auto_20171021_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
