# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0012_remove_piece_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='watch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='secret.Watch'),
        ),
    ]
